# Generated by Django 3.2.21 on 2023-10-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0058_voucher_single_use"),
        ("order", "0174_order_idx_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="voucher_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="discount.vouchercode",
            ),
        ),
    ]
